image: "julia:1"

variables:
  JULIA_DEPOT_PATH: "$CI_PROJECT_DIR/.julia/"

cache:
  paths:
    - .julia/

build:
  stage: build
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - julia --project -e 'using Pkg;
                          Pkg.update();
                          Pkg.instantiate();
                          @time using Pumas;'
    - julia --project -e '@time using Pumas'
  only:
  - master
  - tags
  - external
  - pushes

.template: &template
  stage: test
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - julia --project -e 'using Pkg;
                          Pkg.test("Pumas"; coverage=true);'
    - julia -e 'using Pkg;
                Pkg.add("Coverage");
                using Coverage;
                Codecov.submit_local(process_folder())'
  only:
  - master
  - tags
  - external
  - pushes

test-core:
  <<: *template
  variables:
    GROUP: "Core"

test-parallel:
  <<: *template
  variables:
    GROUP: "Parallel"

test-nca:
  <<: *template
  variables:
    GROUP: "NCA"

test-nlme-basic:
  <<: *template
  variables:
    GROUP: "NLME_Basic"

test-nlme-ml1:
  <<: *template
  variables:
    GROUP: "NLME_ML1"

test-nlme-ml2:
  <<: *template
  variables:
    GROUP: "NLME_ML2"

test-nlme-ml3:
  <<: *template
  variables:
    GROUP: "NLME_ML3"

test-nlme-bayes:
  <<: *template
  variables:
    GROUP: "NLME_Bayes"

test-features:
  <<: *template
  variables:
    GROUP: "Features"

test-ivivc:
  <<: *template
  variables:
    GROUP: "IVIVC"
